FROM ubuntu:18.04      

# nginx 설치
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install nginx

#  포트 지정
EXPOSE 80

# 웹 콘텐츠 배치 - 지금crm


ONBUILD ADD website.tar /var/www/html

# nginx 실행
CMD ["nginx", "-g", "daemon off;"]